### ISSUE TITLE
Convert click coordinates to world coordinates

### ISSUE THREAD

**Issue by OsakaStarbux** [OsakaStarbux/Train-game#1]
Need to convert click coordinates to world coordinates so that the signals (or anything) can be clicked / tapped. Currently broken. The calculations for adjustX and adjustY functions (in helpsers.js) are wrong.

**Comment by grjohan** [comment]
Hi,

I think this solves it:
https://github.com/OsakaStarbux/Train-game/pull/3

But it is still quite ugly as I used magic numbers. I can change it to variables if you want. Do you store the  initial train position relative to the canvas somewhere?

**Comment by OsakaStarbux** [comment]
Fantastic! Thanks! I’m surprised/ glad these are constants. Perhaps I was overthinking it. In sketch.js a canvas is created and I use offsetX and offsetY to place the train left and center in the viewport. The root node of the course where the train starts I recently changed to (0,0) to simplify debugging. It’s in courseTreeA.js.
